### ISSUE TITLE
Question 6

### ISSUE THREAD

**Issue by sdg000** [learn-co-curriculum/phase-1-quiz-working-with-objects-in-javascript#3]
artistInfo.members[0].instruments

This code is correct but was marked wrong. Please verify the code and remark

**Comment by lizbur10** [comment]
Hi @sdg000 ! Your answer was marked incorrect because the question was only looking for the part that comes after the `artistInfo.`. If you look again you should see that instruction included in the question: 

<img width="1000" alt="Screen Shot 2022-06-24 at 9 42 36 AM" src="https://user-images.githubusercontent.com/9666939/175548251-c0642229-459b-4585-b05c-d58b45a73312.png">

If you don't see it, please reopen this issue and include a link to the quiz's Canvas page.

Thanks!
